spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=ms-clientes
spring.cloud.gateway.routes[0].uri=lb://MS-CLIENTES
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clientes/**

spring.cloud.gateway.routes[1].id=ms-reservas
spring.cloud.gateway.routes[1].uri=lb://MS-RESERVAS
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/reservas/**

spring.cloud.gateway.routes[2].id=ms-asistencia
spring.cloud.gateway.routes[2].uri=lb://MS-ASISTENCIA
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/asistencias/**

spring.cloud.gateway.routes[3].id=ms-logros
spring.cloud.gateway.routes[3].uri=lb://MS-LOGROS
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/logros/**

spring.cloud.gateway.routes[4].id=ms-notificaciones
spring.cloud.gateway.routes[4].uri=lb://MS-NOTIFICACIONES
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.routes[5].id=ms-productos
spring.cloud.gateway.routes[5].uri=lb://MS-PRODUCTOS
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.routes[6].id=ms-pagos
spring.cloud.gateway.routes[6].uri=lb://MS-PAGOS
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.routes[7].id=ms-planes
spring.cloud.gateway.routes[7].uri=lb://MS-PLANES
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/planes/**

spring.cloud.gateway.routes[8].id=ms-rutinas
spring.cloud.gateway.routes[8].uri=lb://MS-RUTINAS
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/rutinas/**

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always